import Path from '../../../js/path';

const env_path = new Path();
export default {
    races_2020: {
        hungary: {
            days: '17-19',
            month: 'Jul',
            race_expiry: '2020-07-20',
            sponsor: 'Aramco',
            name: 'Magyar Nagydíj',
            location: 'Budapest, Hungary',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/hungary.gif`,
            flag_alt_text: 'Hungarian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36968',
        },
        britain: {
            days: '31-02',
            month: 'Jul',
            race_expiry: '2020-08-03',
            sponsor: 'Pirelli',
            name: 'British Grand Prix',
            location: 'Silverston, England',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/britain.gif`,
            flag_alt_text: 'British',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36967',
        },
        portugal: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2020-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
    },
    races_2021: {
        hungary: {
            days: '17-19',
            month: 'Jul',
            race_expiry: '2021-07-21',
            sponsor: 'Aramco',
            name: 'Magyar Nagydíj',
            location: 'Budapest, Hungary',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/hungary.gif`,
            flag_alt_text: 'Hungarian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36968',
        },
        britain: {
            days: '31-02',
            month: 'Jul',
            race_expiry: '2021-08-03',
            sponsor: 'Pirelli',
            name: 'British Grand Prix',
            location: 'Silverston, England',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/britain.gif`,
            flag_alt_text: 'British',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36967',
        },
        portugal: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        australia: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        usa: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        belguim: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        japan: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        china: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        brazil: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
        canada: {
            days: '23-25',
            month: 'Oct',
            race_expiry: '2021-10-26',
            sponsor: 'Heineken',
            name: 'Portuguese Grand Prix',
            location: 'Portimao, Portugal',
            country_flag_url: `${env_path.path}/../html/f1/f1-landing-page/images/australia.jpg`,
            flag_alt_text: 'Portugese',
            book_url: 'https://events.hotelsforhope.com/group-event?id=43381',
        },
    },
};
