import Path from '../../../js/path';

const env_path = new Path();
export default {
    races_2020: {
        russia: {
            days: '25-27',
            month: 'Sep',
            race_expiry: '2020-09-27',
            sponsor: 'VTB',
            name: 'Russian Grand Prix',
            location: 'Sochi, Russia',
            country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/russia.jpg`,
            flag_alt_text: 'Russian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36972&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Russia%202020',
        },
        // portugal: {
        //     days: '23-25',
        //     month: 'Oct',
        //     race_expiry: '2020-10-25',
        //     sponsor: 'Heineken',
        //     name: 'Portugese Grand Prix',
        //     location: 'Algarve, Portugal',
        //     country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/`,
        //     flag_alt_text: 'Portugese',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=44099&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Portugal%202020',
        // },
        // turkey: {
        //     days: '13-15',
        //     month: 'Nov',
        //     race_expiry: '2020-11-15',
        //     sponsor: 'DHL',
        //     name: 'Turkish Grand Prix',
        //     location: 'Istanbul, Turkey',
        //     country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/`,
        //     flag_alt_text: 'Turkish',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=44089&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Turkey%202020',
        // },
        bahrain: {
            days: '27-29',
            month: 'Nov',
            race_expiry: '2020-11-29',
            sponsor: 'Gulf Air',
            name: 'Bahrain Grand Prix',
            location: 'Sakhir, Bahrain',
            country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/bahrain.jpg`,
            flag_alt_text: 'Bahrain',
            book_url: 'https://bookrooms.formula1.com/group-event?id=44125&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Bahrain%202020',
        },
        sakhir: {
            days: '4-6',
            month: 'Dec',
            race_expiry: '2020-12-06',
            sponsor: 'Rolex',
            name: 'Turkish Grand Prix',
            location: 'Skahir, Bahrain',
            country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/bahrain.jpg`,
            flag_alt_text: 'Bahrain',
            book_url: 'https://bookrooms.formula1.com/group-event?id=44126&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Sakhir%202020',
        },
        abu_dhabi: {
            days: '11-13',
            month: 'Dec',
            race_expiry: '2020-12-13',
            sponsor: 'Etihad Airways',
            name: 'Abu Dhabi Grand Prix',
            location: 'Yas Island, Abu Dhabi',
            country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/abu-dhabi.jpg`,
            flag_alt_text: 'United Arab Emirates',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36977&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Abu%20Dhabi%202020',
        },
        vietnam: {
            days: 'TBC',
            month: '',
            race_expiry: '2021-01-30',
            sponsor: 'Vinfast',
            name: 'Vietnam Grand Prix',
            location: 'Hanoi, Vietnam',
            country_flag_url: `${env_path.path}/html/f1/f1-landing-page/images/vietnam.jpg`,
            flag_alt_text: 'Vietnamese',
            book_url: 'https://bookrooms.formula1.com/group-event?id=36361&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Vietnam%202020',
        },
    },
};
