import Path from '../../../js/build_tools/path';

const env_path = new Path();
export default {
    // races_2020: {
    //     season_expiry: '2021-12-13',
    //     russia: {
    //         days: '25-27',
    //         month: 'Sep',
    //         race_expiry: '2020-09-27',
    //         sponsor: 'VTB',
    //         name: 'Russian Grand Prix',
    //         location: 'Sochi, Russia',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/russia.jpg`,
    //         flag_alt_text: 'Russian',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=36972&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Russia%202020',
    //     },
    //     portugal: {
    //         days: '23-25',
    //         month: 'Oct',
    //         race_expiry: '2020-10-25',
    //         sponsor: 'Heineken',
    //         name: 'Portuguese Grand Prix',
    //         location: 'Algarve, Portugal',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/portugal.jpg`,
    //         flag_alt_text: 'Portugese',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=44099&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Portugal%202020',
    //     },
    //     turkey: {
    //         days: '13-15',
    //         month: 'Nov',
    //         race_expiry: '2020-11-15',
    //         sponsor: 'DHL',
    //         name: 'Turkish Grand Prix',
    //         location: 'Istanbul, Turkey',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/turkey.jpg`,
    //         flag_alt_text: 'Turkish',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=44089&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Turkey%202020',
    //     },
    //     bahrain: {
    //         days: '27-29',
    //         month: 'Nov',
    //         race_expiry: '2020-11-29',
    //         sponsor: 'Gulf Air',
    //         name: 'Bahrain Grand Prix',
    //         location: 'Sakhir, Bahrain',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/bahrain.jpg`,
    //         flag_alt_text: 'Bahrain',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=44125&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Bahrain%202020',
    //     },
    //     sakhir: {
    //         days: '4-6',
    //         month: 'Dec',
    //         race_expiry: '2020-12-06',
    //         sponsor: 'Rolex',
    //         name: 'Sakhir Grand Prix',
    //         location: 'Sakhir, Bahrain',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/bahrain.jpg`,
    //         flag_alt_text: 'Bahrain',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=44126&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Sakhir%202020',
    //     },
    //     abu_dhabi: {
    //         days: '11-13',
    //         month: 'Dec',
    //         race_expiry: '2020-12-13',
    //         sponsor: 'Etihad Airways',
    //         name: 'Abu Dhabi Grand Prix',
    //         location: 'Yas Island, Abu Dhabi',
    //         country_flag_url: `${env_path.path}/clients/formula_1/images/abu-dhabi.jpg`,
    //         flag_alt_text: 'United Arab Emirates',
    //         book_url: 'https://bookrooms.formula1.com/group-event?id=36977&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Abu%20Dhabi%202020',
    //     },
    //     // vietnam: {
    //     //     days: 'TBC',
    //     //     month: '',
    //     //     race_expiry: '2021-01-30',
    //     //     sponsor: 'Vinfast',
    //     //     name: 'Vietnam Grand Prix',
    //     //     location: 'Hanoi, Vietnam',
    //     //     country_flag_url: `${env_path.path}/clients/formula_1/images/vietnam.jpg`,
    //     //     flag_alt_text: 'Vietnamese',
    //     //     book_url: 'https://bookrooms.formula1.com/group-event?id=36361&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Vietnam%202020',
    //     // },
    // },
    races_2021: {
        season_expiry: '2021-12-06',
        bahrain: {
            days: '26-28',
            month: 'Mar',
            race_expiry: '2021-03-29',
            sponsor: '',
            name: 'Bahrain Grand Prix',
            location: 'Sakhir, Bahrain',
            country_flag_url: `${env_path.path}/clients/formula_1/images/bahrain.jpg`,
            flag_alt_text: 'Bahrain',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45300&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Bahrain%202021',
        },
        imola: {
            days: '16-18',
            month: 'Apr',
            race_expiry: '2021-04-19',
            sponsor: '',
            name: 'Emilia Romagna Grand Prix',
            location: 'Imola, Italy',
            country_flag_url: `${env_path.path}/clients/formula_1/images/italy.jpg`,
            flag_alt_text: 'Italian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=47086&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Imola%202021',
        },
        // portugal: {
        //     days: '30-2',
        //     month: 'May',
        //     race_expiry: '2021-05-03',
        //     sponsor: '',
        //     name: 'Portuguese Grand Prix',
        //     location: 'Autódromo Internacional do Algarve',
        //     country_flag_url: `${env_path.path}/clients/formula_1/images/portugal.jpg`,
        //     flag_alt_text: 'Portugese',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=47085&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Portugal%202021',
        // },
        // china: {
        //     days: '9-11',
        //     month: 'Apr',
        //     race_expiry: '2021-04-12',
        //     sponsor: '',
        //     name: 'Chinese Grand Prix',
        //     location: 'Shanghai, China',
        //     country_flag_url: `${env_path.path}/clients/formula_1/images/china.gif`,
        //     flag_alt_text: 'Chinese',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=45301&utm_source=Website&utm_medium=Index%20Page&utm_campaign=China%202021',
        // },
        spain: {
            days: '7-9',
            month: 'May',
            race_expiry: '2021-05-10',
            sponsor: '',
            name: 'Spanish Grand Prix',
            location: 'Catalunya, Spain',
            country_flag_url: `${env_path.path}/clients/formula_1/images/spain.gif`,
            flag_alt_text: 'Spanish',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45302&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Spain%202021',
        },
        monaco: {
            days: '21-23',
            month: 'May',
            race_expiry: '2021-05-24',
            sponsor: '',
            name: 'Monaco Grand Prix',
            location: 'Monte Carlo, Monaco',
            country_flag_url: `${env_path.path}/clients/formula_1/images/monaco.jpg`,
            flag_alt_text: 'Monaco',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45303&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Monaco%202021',
        },
        azerbaijan: {
            days: '4-6',
            month: 'Jun',
            race_expiry: '2021-06-07',
            sponsor: '',
            name: 'Azerbaijan Grand Prix',
            location: 'Baku, Azerbaijan',
            country_flag_url: `${env_path.path}/clients/formula_1/images/azerbaijan.jpg`,
            flag_alt_text: 'Azerbaijan',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45326&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Azerbaijan%202021',
        },
        canada: {
            days: '11-13',
            month: 'Jun',
            race_expiry: '2021-06-14',
            sponsor: '',
            name: 'Canadian Grand Prix',
            location: 'Montreal, Canada',
            country_flag_url: `${env_path.path}/clients/formula_1/images/canada.jpg`,
            flag_alt_text: 'Canadian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45328&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Canada%202021',
        },
        france: {
            days: '18-20',
            month: 'Jun',
            race_expiry: '2021-06-21',
            sponsor: '',
            name: 'French Grand Prix',
            location: 'La Castellet, France ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/france.png`,
            flag_alt_text: 'French',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45333&utm_source=Website&utm_medium=Index%20Page&utm_campaign=France%202021',
        },
        austria: {
            days: '2-4',
            month: 'Jul',
            race_expiry: '2021-07-05',
            sponsor: '',
            name: 'Austrian Grand Prix',
            location: 'Styria, Austria ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/austria.gif`,
            flag_alt_text: 'Austrian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45331&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Austria%202021',
        },
        britain: {
            days: '16-18',
            month: 'Jul',
            race_expiry: '2021-07-19',
            sponsor: '',
            name: 'British Grand Prix',
            location: 'Silverstone, England',
            country_flag_url: `${env_path.path}/clients/formula_1/images/britain.gif`,
            flag_alt_text: 'British',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45334&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Great%20Britain%202021',
        },
        hungary: {
            days: '30-1',
            month: 'Aug',
            race_expiry: '2021-08-02',
            sponsor: '',
            name: 'Hungarian Grand Prix',
            location: 'Budapest, Hungary ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/hungary.gif`,
            flag_alt_text: 'Hungarian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45335&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Hungary%202021',
        },
        belgium: {
            days: '27-29',
            month: 'Aug',
            race_expiry: '2021-08-30',
            sponsor: '',
            name: 'Belgian Grand Prix',
            location: 'Stavelot, Belgium ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/belgium.jpg`,
            flag_alt_text: 'Belgian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45306&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Belgium%202021',
        },
        netherlands: {
            days: '3-5',
            month: 'Sep',
            race_expiry: '2021-09-06',
            sponsor: '',
            name: 'Dutch Grand Prix',
            location: 'Zandvoort, Netherlands',
            country_flag_url: `${env_path.path}/clients/formula_1/images/netherlands.jpg`,
            flag_alt_text: 'Dutch',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45295&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Dutch%202021',
        },
        italy: {
            days: '10-12',
            month: 'Sep',
            race_expiry: '2021-09-13',
            sponsor: '',
            name: 'Italian Grand Prix',
            location: 'Monza, Italy ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/italy.jpg`,
            flag_alt_text: 'Italian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45307&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Italy%202021',
        },
        russia: {
            days: '24-26',
            month: 'Sep',
            race_expiry: '2021-09-27',
            sponsor: '',
            name: 'Russian Grand Prix',
            location: 'Sochi, Russia ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/russia.jpg`,
            flag_alt_text: 'Russian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45336&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Russia%202021',
        },
        // singapore: {
        //     days: '1-3',
        //     month: 'Oct',
        //     race_expiry: '2021-10-04',
        //     sponsor: '',
        //     name: 'Singapore Grand Prix',
        //     location: 'Marina Bay, Singapore',
        //     country_flag_url: `${env_path.path}/clients/formula_1/images/singapore.svg`,
        //     flag_alt_text: 'Singaporean',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=45308&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Singapore%202021',
        // },
        japan: {
            days: '8-10',
            month: 'Oct',
            race_expiry: '2021-10-11',
            sponsor: '',
            name: 'Japanese Grand Prix',
            location: 'Sazuka, Japan ',
            country_flag_url: `${env_path.path}/clients/formula_1/images/japan.jpg`,
            flag_alt_text: 'Japanese',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45337&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Japan%202021',
        },
        usa: {
            days: '22-24',
            month: 'Oct',
            race_expiry: '2021-10-25',
            sponsor: '',
            name: 'United States Grand Prix',
            location: 'Austin, Texas, United States',
            country_flag_url: `${env_path.path}/clients/formula_1/images/us.jpg`,
            flag_alt_text: 'United States',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45310&utm_source=Website&utm_medium=Index%20Page&utm_campaign=United%20States%202021',
        },
        mexico: {
            days: '29-31',
            month: 'Oct',
            race_expiry: '2021-11-01',
            sponsor: '',
            name: 'Mexican Grand Prix',
            location: 'Mexico City, Mexico',
            country_flag_url: `${env_path.path}/clients/formula_1/images/mexico.jpg`,
            flag_alt_text: 'Mexican',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45313&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Mexico%202021',
        },
        brazil: {
            days: '5-7',
            month: 'Nov',
            race_expiry: '2021-11-15',
            sponsor: '',
            name: 'Brazilian Grand Prix',
            location: 'Brazil',
            country_flag_url: `${env_path.path}/clients/formula_1/images/brazil.png`,
            flag_alt_text: 'Brazilian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45315&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Brazil%202021',
        },
        australia: {
            days: '19-21',
            month: 'Nov',
            race_expiry: '2021-11-22',
            sponsor: '',
            name: 'Australian Grand Prix',
            location: 'Melbourne, Australia',
            country_flag_url: `${env_path.path}/clients/formula_1/images/australia.jpg`,
            flag_alt_text: 'Australian',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45297&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Australia%202021',
        },
        // saudi_arabia: {
        //     days: '3-5',
        //     month: 'Dec',
        //     race_expiry: '2021-12-06',
        //     sponsor: '',
        //     name: 'Saudi Arabian Grand Prix',
        //     location: 'Jeddah, Saudi Arabia',
        //     country_flag_url: `${env_path.path}/clients/formula_1/images/saudi_arabia.jpg`,
        //     flag_alt_text: 'Saudi Arabian',
        //     book_url: 'https://bookrooms.formula1.com/group-event?id=45315&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Saudi%20Arabia%202021',
        // },
        abu_dhabi: {
            days: '10-12',
            month: 'Dec',
            race_expiry: '2021-12-13',
            sponsor: '',
            name: 'Abu Dhabi Grand Prix',
            location: 'Yas Island, Abu Dhabi, UAE',
            country_flag_url: `${env_path.path}/clients/formula_1/images/abu-dhabi.jpg`,
            flag_alt_text: 'UAE',
            book_url: 'https://bookrooms.formula1.com/group-event?id=45322&utm_source=Website&utm_medium=Index%20Page&utm_campaign=Abu%20Dhabi%202021',
        },
    },
};
